openapi: "3.0.0"
info:
  version: 1.0.0
  title: Immersio Server API
  license:
    name: MIT
servers:
  - url: immersio-server.azurewebsites.net
paths:
  /lessons/{lessonId}:
    get:
      summary: Content for a specific lesson
      operationId: showLessonById
      tags:
        - Lessons
      parameters:
        - name: lessonId
          in: path
          required: true
          description: The id of the lesson to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Lesson"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Lesson:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
